package com.github.mrzhqiang;

import javax.swing.*;

public class RandallCenter {
  public JPanel root;
  private JTabbedPane content;
  private JPanel configGuide;
  private JPanel dataBackup;
  private JPanel dataClear;
  private JTabbedPane configTabbed;
  private JPanel step1;
  private JPanel step2;
  private JPanel step3;
  private JPanel step4;
  private JPanel step5;
  private JPanel step6;
  private JPanel step7;
  private JPanel step8;
  private JPanel step9;
  private JCheckBox dbServer;
  private JCheckBox loginSrv;
  private JCheckBox m2Server;
  private JCheckBox logServer;
  private JCheckBox runGate;
  private JCheckBox selGate;
  private JCheckBox loginGate;
  private JCheckBox rankPlugin;
  private JComboBox startMode;
  private JSpinner startHours;
  private JLabel hoursLabel;
  private JSpinner startMinute;
  private JLabel minuteLabel;
  private JList infoList;
  private JButton startGame;
  private JPanel serverControl;
  private JPanel startControl;
  private JPanel stratInfo;
  private JPanel startPanel;
  private JPanel timeControl;
  private JPanel gameDirDbSetting;
  private JLabel serverDirLabel;
  private JLabel dbNameLabel;
  private JLabel serverNameLabel;
  private JLabel serverAddressLabel;
  private JTextField serverDirField;
  private JTextField dbNameField;
  private JButton defaultSettingBtn;
  private JTextField serverNameField;
  private JTextField serverAddressField;
  private JCheckBox 关闭服务器五行功能CheckBox;
    private JButton 默认设置Button;
    private JTextField a7000TextField;
    private JSpinner spinner1;
    private JSpinner spinner2;
    private JCheckBox 启动登陆网关CheckBox;
    private JButton 上一步Button;
    private JButton 下一步Button1;
    private JButton 重加载Button;
    private JButton 下一步Button;
}
